# Generated by Django 4.2.3 on 2023-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Sage', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
